### ISSUE TITLE
About One hot encoder 

### ISSUE THREAD

**Issue by d-ghale** [ELToulemonde/dataPreparation#44]
Is there a reason why "one_hot_encoder" creates the columns in integer format instead of logical ? 

I need help to find an efficient way to convert the columns I created using "one_hot_encoder" into `lgl` format without expliciting writing out the list of columns.  

Thanks!

**Comment by ELToulemonde** [comment]
Hi,

Hmm... I don't really know. Why not? Do you have a use case where 0 and 1 are painful?

**Comment by d-ghale** [comment]
Yes, say I create a numeric column called `total_count` that contains 0 or 1.  I use `one_hot_encoder` to create a logical column but it is expressed as 0 or 1, not TRUE or FALSE.   When I   use `whichAreInDouble` I get a false result saying these two columns are the same.

**Comment by ELToulemonde** [comment]
Ok I say

- First, I don't realy see why it is a problem, since both columns contains exactly the same information (for example function `whichAreBijection` will drop it even if it is TRUE/FALSE or 0/1.

- Second, here is a dirty fix; pass the column you wish to fix into argument `keep_cols` in `whichAreDouble` 

- Last, I added the argument `type` into `one_hot_encoder`, this argument let's you choose between integer, numeric and logical for the type of the result. It will be released in future CRAN release.

Until CRAN release, you can have this feature by installing package directly from github

```
library(devtools)
install_github("ELToulemonde/dataPreparation")
```

Hope I answered your question.

If you have any other question/remarks please don't hesitate.

I close. 

Emmanuel-Lin

**Comment by d-ghale** [comment]
Thanks! Yes, `whichAreBijection` will drop it even if it is TRUE/FALSE or 0/1. I am using `fastFilterVariables` with type = 2 to drop constant and double columns. Your update solved my problem. 

Thank You!
